# Generated by Django 3.2.3 on 2021-07-18 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('link', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
                ('off_price', models.IntegerField()),
                ('off_p', models.IntegerField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(choices=[('amazon', 'Amazon'), ('flifkart', 'Flifkart'), ('ajio', 'Ajio')], default='amazon', max_length=100)),
                ('company', models.CharField(choices=[('puma', 'Puma'), ('adidas', 'Adidas'), ('nike', 'Nike'), ('h&m', 'H&M')], default='null', max_length=100)),
                ('item', models.CharField(choices=[('t-shirt', 'T-short'), ('shirt', 'Shirt'), ('pant', 'Pant'), ('shoe', 'Shoe')], default='null', max_length=100)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
    ]
